#!/usr/bin/env node
// Regenerate the doc cards in index.html from the HTML files under hermes/.
// The tree is scanned recursively, but hermes/private/ is skipped: those pages
// are written for one client and stay unlisted. They remain reachable by URL.
//
// Each page declares its own section:  <meta name="doc-category" content="Payment">
// Pages without one land under "Other".
//
// Run after adding or renaming a hermes doc:  node build-index.cjs
// Cards are written between the <!-- DOCS:START --> and <!-- DOCS:END --> markers.

const fs = require("fs");
const path = require("path");

const root = __dirname;
const hermesDir = path.join(root, "hermes");
const indexFile = path.join(root, "index.html");

const START = "<!-- DOCS:START";
const END = "<!-- DOCS:END -->";

// Sections in reading order: connect the money first, then the channels.
// Anything else sorts alphabetically after these.
const SECTIONS = ["Payment", "Messaging", "Calendar"];
const FALLBACK = "Other";

// Pull the text of the first matching tag, HTML-unescaped just enough for titles.
function firstMatch(html, re) {
  const m = html.match(re);
  return m ? m[1].trim() : "";
}

// Client-only pages live here and never appear on the index.
const PRIVATE_DIR = path.join(hermesDir, "private");

// Every public *.html under hermes/, at any depth, as absolute paths.
function walk(dir) {
  if (dir === PRIVATE_DIR) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) return walk(full);
    return e.isFile() && e.name.endsWith(".html") ? [full] : [];
  });
}

const docs = walk(hermesDir)
  .map((file) => {
    const html = fs.readFileSync(file, "utf8");
    const slug = path
      .relative(hermesDir, file)
      .replace(/\.html$/, "")
      .split(path.sep)
      .join("/");
    return {
      slug,
      url: `/hermes/${slug}`,
      title: firstMatch(html, /<title>([^<]*)<\/title>/i) || slug,
      section:
        firstMatch(html, /<meta\s+name="doc-category"\s+content="([^"]*)"\s*\/?>/i) || FALLBACK,
    };
  })
  .sort((a, b) => a.title.localeCompare(b.title));

const bySection = new Map();
for (const doc of docs) {
  if (!bySection.has(doc.section)) bySection.set(doc.section, []);
  bySection.get(doc.section).push(doc);
}

const rank = (name) => {
  const i = SECTIONS.indexOf(name);
  return i === -1 ? SECTIONS.length : i;
};
const sections = [...bySection.keys()].sort(
  (a, b) => rank(a) - rank(b) || a.localeCompare(b)
);

const card = (d) =>
  `  <a class="card" href="${d.url}">\n` +
  `    <h3>${d.title}</h3>\n` +
  `    <p>docs.41labs.ai${d.url}</p>\n` +
  `  </a>`;

const body = sections
  .map((name) => `  <h2>Hermes · ${name}</h2>\n\n${bySection.get(name).map(card).join("\n\n")}`)
  .join("\n\n");

const block =
  `${START} — generated by build-index.cjs from hermes/**/*.html ` +
  `(public pages only; hermes/private/ is excluded). Do not edit by hand. -->\n` +
  `${body}\n  ${END}`;

const index = fs.readFileSync(indexFile, "utf8");
const re = new RegExp(`${START}[\\s\\S]*?${END}`);
if (!re.test(index)) {
  console.error(`Markers ${START} ... ${END} not found in index.html`);
  process.exit(1);
}
fs.writeFileSync(indexFile, index.replace(re, block));
console.log(
  `index.html: wrote ${docs.length} card(s) in ${sections.length} section(s) — ` +
    sections.map((s) => `${s}: ${bySection.get(s).length}`).join(", ")
);
