#!/usr/bin/env node
// Regenerate the Hermes card list in index.html from the HTML files that sit
// directly inside hermes/. Subdirectories are never scanned, so anything under
// hermes/private/ (per-client, unlisted) can never appear on the public index.
//
// Run after adding or renaming a top-level hermes doc:  node build-index.cjs
// Cards are written between the <!-- DOCS:START --> and <!-- DOCS:END --> markers.

const fs = require("fs");
const path = require("path");

const root = __dirname;
const hermesDir = path.join(root, "hermes");
const indexFile = path.join(root, "index.html");

const START = "<!-- DOCS:START";
const END = "<!-- DOCS:END -->";

// Pull the text of the first matching tag, HTML-unescaped just enough for titles.
function firstMatch(html, re) {
  const m = html.match(re);
  return m ? m[1].trim() : "";
}

// Top-level *.html files only. withFileTypes lets us skip the private/ dir.
const docs = fs
  .readdirSync(hermesDir, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith(".html"))
  .map((e) => {
    const html = fs.readFileSync(path.join(hermesDir, e.name), "utf8");
    const slug = e.name.replace(/\.html$/, "");
    const title = firstMatch(html, /<title>([^<]*)<\/title>/i) || slug;
    return { slug, title, url: `/hermes/${slug}` };
  })
  .sort((a, b) => a.title.localeCompare(b.title));

const cards = docs
  .map(
    (d) =>
      `  <a class="card" href="${d.url}">\n` +
      `    <h3>${d.title}</h3>\n` +
      `    <p>docs.41labs.ai${d.url}</p>\n` +
      `  </a>`
  )
  .join("\n\n");

const block =
  `${START} — generated by build-index.cjs from hermes/*.html ` +
  `(top level only; private/ is never scanned). Do not edit by hand. -->\n` +
  `${cards}\n  ${END}`;

const index = fs.readFileSync(indexFile, "utf8");
const re = new RegExp(`${START}[\\s\\S]*?${END}`);
if (!re.test(index)) {
  console.error(`Markers ${START} ... ${END} not found in index.html`);
  process.exit(1);
}
fs.writeFileSync(indexFile, index.replace(re, block));
console.log(`index.html: wrote ${docs.length} card(s) — ${docs.map((d) => d.slug).join(", ")}`);
